package cni

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"time"

	"github.com/wizhao/dpu-sim/pkg/linux"
)

const (
	// DefaultOVNImage is the default OVN-Kubernetes image
	DefaultOVNImage = "ghcr.io/ovn-kubernetes/ovn-kubernetes/ovn-kube-fedora:master"
)

// runDaemonsetScript runs the OVN-Kubernetes daemonset.sh script to generate manifests
func (m *CNIManager) runDaemonsetScript(ovnkRepoPath, apiServerURL, podCIDR, serviceCIDR, ovnImage string) error {
	daemonsetScript := filepath.Join(ovnkRepoPath, "dist", "images", "daemonset.sh")

	if _, err := os.Stat(daemonsetScript); os.IsNotExist(err) {
		return fmt.Errorf("daemonset.sh script not found at %s", daemonsetScript)
	}

	if err := os.Chmod(daemonsetScript, 0755); err != nil {
		return fmt.Errorf("failed to make daemonset.sh executable: %w", err)
	}

	args := []string{
		fmt.Sprintf("--image=%s", ovnImage),
		fmt.Sprintf("--net-cidr=%s", podCIDR),
		fmt.Sprintf("--svc-cidr=%s", serviceCIDR),
		fmt.Sprintf("--k8s-apiserver=%s", apiServerURL),
		"--gateway-mode=shared",
		"--dummy-gateway-bridge=false",
		"--gateway-options=",
		"--enable-ipsec=false",
		"--hybrid-enabled=false",
		"--disable-snat-multiple-gws=false",
		"--disable-forwarding=false",
		"--ovn-encap-port=",
		"--disable-pkt-mtu-check=false",
		"--ovn-empty-lb-events=false",
		"--multicast-enabled=false",
		"--ovn-master-count=1",
		"--ovn-unprivileged-mode=no",
		"--master-loglevel=5",
		"--node-loglevel=5",
		"--dbchecker-loglevel=5",
		"--ovn-loglevel-northd=-vconsole:info -vfile:info",
		"--ovn-loglevel-nb=-vconsole:info -vfile:info",
		"--ovn-loglevel-sb=-vconsole:info -vfile:info",
		"--ovn-loglevel-controller=-vconsole:info",
		"--ovnkube-libovsdb-client-logfile=",
		"--ovnkube-config-duration-enable=true",
		"--admin-network-policy-enable=true",
		"--egress-ip-enable=true",
		"--egress-ip-healthcheck-port=9107",
		"--egress-firewall-enable=true",
		"--egress-qos-enable=true",
		"--egress-service-enable=true",
		"--v4-join-subnet=100.64.0.0/16",
		"--v6-join-subnet=fd98::/64",
		"--v4-masquerade-subnet=169.254.0.0/17",
		"--v6-masquerade-subnet=fd69::/112",
		"--v4-transit-subnet=100.88.0.0/16",
		"--v6-transit-subnet=fd97::/64",
		"--ex-gw-network-interface=",
		"--multi-network-enable=false",
		"--network-segmentation-enable=false",
		"--preconfigured-udn-addresses-enable=false",
		"--route-advertisements-enable=false",
		"--advertise-default-network=false",
		"--advertised-udn-isolation-mode=strict",
		"--ovnkube-metrics-scale-enable=false",
		"--compact-mode=false",
		"--enable-multi-external-gateway=true",
		"--enable-ovnkube-identity=true",
		"--enable-persistent-ips=true",
		"--network-qos-enable=false",
		"--mtu=1400",
		"--enable-dnsnameresolver=false",
		"--enable-observ=false",
	}

	fmt.Printf("Running daemonset.sh to generate manifests...\n")
	cmd := exec.Command(daemonsetScript, args...)
	cmd.Dir = filepath.Dir(daemonsetScript)

	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("daemonset.sh failed stdout: %s, stderr: %s", output, err)
	}

	fmt.Printf("✓ daemonset.sh completed successfully, Output: %s\n", output)
	return nil
}

// applyOVNKubernetesManifests applies the OVN-Kubernetes manifests generated by daemonset.sh
func (m *CNIManager) applyOVNKubernetesManifests(ovnPath string) error {
	yamlDir := filepath.Join(ovnPath, "dist", "yaml")

	// Check if yaml directory exists
	if _, err := os.Stat(yamlDir); os.IsNotExist(err) {
		return fmt.Errorf("YAML directory not found at %s", yamlDir)
	}

	// CRD manifests to apply first
	crdManifests := []string{
		"k8s.ovn.org_egressfirewalls.yaml",
		"k8s.ovn.org_egressips.yaml",
		"k8s.ovn.org_egressqoses.yaml",
		"k8s.ovn.org_egressservices.yaml",
		"k8s.ovn.org_adminpolicybasedexternalroutes.yaml",
		"k8s.ovn.org_networkqoses.yaml",
		"k8s.ovn.org_userdefinednetworks.yaml",
		"k8s.ovn.org_clusteruserdefinednetworks.yaml",
		"k8s.ovn.org_routeadvertisements.yaml",
		"k8s.ovn.org_clusternetworkconnects.yaml",
	}

	// External CRDs (ANP & BANP)
	externalCRDs := []string{
		"https://raw.githubusercontent.com/kubernetes-sigs/network-policy-api/v0.1.5/config/crd/experimental/policy.networking.k8s.io_adminnetworkpolicies.yaml",
		"https://raw.githubusercontent.com/kubernetes-sigs/network-policy-api/v0.1.5/config/crd/experimental/policy.networking.k8s.io_baselineadminnetworkpolicies.yaml",
	}

	// Setup and RBAC manifests
	setupManifests := []string{
		"ovn-setup.yaml",
		"rbac-ovnkube-identity.yaml",
		"rbac-ovnkube-cluster-manager.yaml",
		"rbac-ovnkube-master.yaml",
		"rbac-ovnkube-node.yaml",
		"rbac-ovnkube-db.yaml",
	}

	// Global zone manifests (after labeling nodes)
	globalZoneManifests := []string{
		"ovs-node.yaml",
		"ovnkube-db.yaml",
		"ovnkube-identity.yaml",
		"ovnkube-master.yaml",
		"ovnkube-node.yaml",
	}

	fmt.Printf("  Applying OVN-Kubernetes CRD manifests...\n")
	for _, manifest := range crdManifests {
		manifestPath := filepath.Join(yamlDir, manifest)
		content, err := os.ReadFile(manifestPath)
		if err != nil {
			return fmt.Errorf("failed to read manifest %s: %w", manifest, err)
		}
		if err := m.k8sClient.ApplyManifest(content); err != nil {
			return fmt.Errorf("failed to apply manifest %s: %w", manifest, err)
		}
		fmt.Printf("    ✓ Applied %s\n", manifest)
	}

	fmt.Printf("  Applying external CRD manifests...\n")
	for _, url := range externalCRDs {
		if err := m.k8sClient.ApplyManifestFromURL(url); err != nil {
			return fmt.Errorf("failed to apply external CRD from %s: %w", url, err)
		}
	}

	fmt.Printf("  Applying OVN-Kubernetes setup manifests...\n")
	for _, manifest := range setupManifests {
		manifestPath := filepath.Join(yamlDir, manifest)
		content, err := os.ReadFile(manifestPath)
		if err != nil {
			return fmt.Errorf("failed to read manifest %s: %w", manifest, err)
		}
		if err := m.k8sClient.ApplyManifest(content); err != nil {
			return fmt.Errorf("failed to apply manifest %s: %w", manifest, err)
		}
		fmt.Printf("    ✓ Applied %s\n", manifest)
	}

	// Label master nodes for OVN HA
	if err := m.labelOVNMasterNodes(); err != nil {
		return fmt.Errorf("failed to label master nodes: %w", err)
	}

	fmt.Printf("  Applying OVN-Kubernetes global zone manifests...\n")
	for _, manifest := range globalZoneManifests {
		manifestPath := filepath.Join(yamlDir, manifest)
		content, err := os.ReadFile(manifestPath)
		if err != nil {
			return fmt.Errorf("failed to read manifest %s: %w", manifest, err)
		}
		if err := m.k8sClient.ApplyManifest(content); err != nil {
			return fmt.Errorf("failed to apply manifest %s: %w", manifest, err)
		}
		fmt.Printf("    ✓ Applied %s\n", manifest)
	}

	return nil
}

// labelOVNMasterNodes labels master nodes for OVN HA deployment
func (m *CNIManager) labelOVNMasterNodes() error {
	fmt.Printf("  Labeling master nodes for OVN HA...\n")

	nodes, err := m.k8sClient.GetNodes()
	if err != nil {
		return fmt.Errorf("failed to get nodes: %w", err)
	}

	for _, node := range nodes {
		// Label node using kubectl (more reliable for label operations)
		cmd := exec.Command("kubectl", "label", "node", node.Name,
			"k8s.ovn.org/ovnkube-db=true",
			"node-role.kubernetes.io/control-plane=",
			"--overwrite")
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("failed to label node %s: %w", node.Name, err)
		}
		fmt.Printf("    ✓ Labeled node %s\n", node.Name)

		// Remove taints using kubectl (best effort)
		exec.Command("kubectl", "taint", "node", node.Name,
			"node-role.kubernetes.io/master:NoSchedule-").Run()
		exec.Command("kubectl", "taint", "node", node.Name,
			"node-role.kubernetes.io/control-plane:NoSchedule-").Run()
		fmt.Printf("    ✓ Removed taints from node %s\n", node.Name)
	}

	fmt.Printf("  ✓ Master nodes labeled for OVN HA\n")
	return nil
}

// installOVNKubernetes installs OVN-Kubernetes CNI using the local source code
func (m *CNIManager) installOVNKubernetes(clusterName string) error {
	fmt.Println("  Installing OVN-Kubernetes CNI...")

	// Get cluster configuration
	podCIDR := "10.244.0.0/16"
	serviceCIDR := "10.96.0.0/12"
	apiServerURL := "https://127.0.0.1:6443" // Default, should be overridden

	if m.config != nil {
		clusterCfg := m.config.GetClusterConfig(clusterName)
		if clusterCfg != nil {
			if clusterCfg.PodCIDR != "" {
				podCIDR = clusterCfg.PodCIDR
			}
			if clusterCfg.ServiceCIDR != "" {
				serviceCIDR = clusterCfg.ServiceCIDR
			}
		}
	}

	fmt.Printf("  Using Pod CIDR: %s, Service CIDR: %s\n", podCIDR, serviceCIDR)

	// Ensure OVN-Kubernetes source is available
	ovnPath, err := linux.EnsureOVNKubernetesSource()
	if err != nil {
		return fmt.Errorf("failed to ensure OVN-Kubernetes source: %w", err)
	}

	// Run daemonset.sh to generate manifests
	if err := m.runDaemonsetScript(ovnPath, apiServerURL, podCIDR, serviceCIDR, DefaultOVNImage); err != nil {
		return fmt.Errorf("failed to run daemonset.sh: %w", err)
	}

	// Apply the generated manifests
	if err := m.applyOVNKubernetesManifests(ovnPath); err != nil {
		return fmt.Errorf("failed to apply OVN-Kubernetes manifests: %w", err)
	}

	fmt.Println("✓ OVN-Kubernetes installed")

	// Wait for OVN pods to be ready
	if err := m.k8sClient.WaitForPodsReady("ovn-kubernetes", "", 5*time.Minute); err != nil {
		fmt.Printf("Warning: OVN-Kubernetes pods may not be ready: %v\n", err)
	}

	return nil
}
